#!/usr/bin/env bash
#print strings on each line
echo "one"
echo "two"
echo "three"
echo "four"
echo "five"
#create a text file with today's date
filename=$(date)-file.txt
echo "file created: $filename"
echo "one" > "$filename"
echo "two" >> "$filename"
echo "three" >> "$filename"
echo "four" >> "$filename"
echo "five" >> "$filename"
